version: '2'
services:
  interfaceserver:
    build: .
    command: /app/entrypoint-interface.sh
    user: app
    working_dir: /app
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET_KEY
      - vhost=shojun2.ocom.com.au
    network_mode: bridge
    external_links:
      - database: pgdata


  workerserver:
    build: .
    user: app
    working_dir: /app
    command: /app/entrypoint-worker.sh
    environment:
      - DJANGO_SECRET_KEY
    network_mode: bridge
    external_links:
      - database: pgdata

  redis:
    image: redis:3.0-alpine
    network_mode: bridge
